version: "3"

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:latest
    container_name: my_db
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: me
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - a-tink-test
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin  # Логин
      MINIO_ROOT_PASSWORD: minioadmin  # Пароль
    volumes:
      - ./minio_data:/data  # Хранилище данных
    command: server /data --console-address ":9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  a-tink-test:
    driver: bridge