spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.url}:${db.port}/${db.name}
    password: ${db.pass}
    username: ${db.username}

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN


  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    password: ${db.pass}
    user: ${db.username}

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    root: info